### ISSUE TITLE
Discuss how the build system will be constructed and the code structure

### ISSUE THREAD

**Issue by 0xsuu** [Llama-Group/Project-Llama#10]
Build: CMake
Code: Folder and stuff
Test: How to test algorithm (use example folder?)

**Comment by BlueCocoa** [comment]
How about imitating Google's style?

For example, [google/benchmark](https://github.com/google/benchmark)

**Comment by 0xsuu** [comment]
Sounds good, need to look into the integration of that benchmark.

Moved to #11
