### ISSUE TITLE
Add null pointer checking for generateSingleDatum

### ISSUE THREAD

**Issue by 0xsuu** [Llama-Group/Project-Llama#130]
Try pass a nullptr and a valid case, boom, crashed!

**Comment by 0xsuu** [comment]
Should be able to throw a runtime exception, and add test to it in UtilDGUT.cpp(abbr.) as well. @Giolno

**Comment by BlueCocoa** [comment]
IMHO, it better to use reference instead of pointer.

**Comment by 0xsuu** [comment]
Using pass by ref now.
