### ISSUE TITLE
Add test example and wiki for cryptography

### ISSUE THREAD

**Issue by 0xsuu** [Llama-Group/Project-Llama#16]
@BlueCocoa 

And better not depend on openssl, just write your own RSA.

**Comment by 0xsuu** [comment]
@BlueCocoa Add check of openssl lib in cmake.

**Comment by 0xsuu** [comment]
Done, maybe?

**Comment by BlueCocoa** [comment]
Ok, I'll try to write RSA later, but it would be safer if we use libcrypto.
