### ISSUE TITLE
Add a class of generating test data

### ISSUE THREAD

**Issue by ghost** [Llama-Group/Project-Llama#61]
Designing structure: be extendable
Think where it can be used

**Comment by 0xsuu** [comment]
The source file should be named as TestDataGenerator.h and TestDataGenerator.cpp. They should be placed in Project-Llama/llama_cpp/test/ 
Note: test is a new directory that you need to create(mkdir).

The class should be able to generate vectors of various types. Requirements are:
- [x] Generating vectors of random int/double/string/customClass. (hint: use template can put all of them in one function)
- [x] Generating vectors of continuous int/double/string/customClass. Provide option for ascending or descending. string in ascii sequence.

**Comment by 0xsuu** [comment]
Complete what stated in #84 , check #63 's comments.

**Comment by 0xsuu** [comment]
Done.
