### ISSUE TITLE
Complete Xcode functionality

### ISSUE THREAD

**Issue by 0xsuu** [Llama-Group/Project-Llama#74]
- [x] Add Resource move for RSA @BlueCocoa 
- [x] Add lint target or script or sth @BlueCocoa @al1enSuu
- [x] Fix generated binary not shown in "Products" (red mark). @BlueCocoa 
- [x] Xcode not showing .h file. @BlueCocoa 
  Tick after completion.

**Comment by BlueCocoa** [comment]
Xcode not showing .h file.
Now fixed, pls see #77

**Comment by BlueCocoa** [comment]
Add Resource move for RSA
Now fixed, pls see #71

**Comment by 0xsuu** [comment]
@Sunbelife reported No. 3 is working on his machine.

**Comment by 0xsuu** [comment]
Done.
